package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CHEMICAL.
 */
public class Chemical {

    private Long chemicalID;
    private Integer chemicalType;
    private Integer cropStage;
    private Integer activeIngredient;
    private String agent;
    private String manufacturer;
    private Integer pHI;
    private String productTradeName;
    private Integer rate;
    private String reasonForUse;
    private String registrationNumber;

    public Chemical() {
    }

    public Chemical(Long chemicalID) {
        this.chemicalID = chemicalID;
    }

    public Chemical(Long chemicalID, Integer chemicalType, Integer cropStage, Integer activeIngredient, String agent, String manufacturer, Integer pHI, String productTradeName, Integer rate, String reasonForUse, String registrationNumber) {
        this.chemicalID = chemicalID;
        this.chemicalType = chemicalType;
        this.cropStage = cropStage;
        this.activeIngredient = activeIngredient;
        this.agent = agent;
        this.manufacturer = manufacturer;
        this.pHI = pHI;
        this.productTradeName = productTradeName;
        this.rate = rate;
        this.reasonForUse = reasonForUse;
        this.registrationNumber = registrationNumber;
    }

    public Long getChemicalID() {
        return chemicalID;
    }

    public void setChemicalID(Long chemicalID) {
        this.chemicalID = chemicalID;
    }

    public Integer getChemicalType() {
        return chemicalType;
    }

    public void setChemicalType(Integer chemicalType) {
        this.chemicalType = chemicalType;
    }

    public Integer getCropStage() {
        return cropStage;
    }

    public void setCropStage(Integer cropStage) {
        this.cropStage = cropStage;
    }

    public Integer getActiveIngredient() {
        return activeIngredient;
    }

    public void setActiveIngredient(Integer activeIngredient) {
        this.activeIngredient = activeIngredient;
    }

    public String getAgent() {
        return agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Integer getPHI() {
        return pHI;
    }

    public void setPHI(Integer pHI) {
        this.pHI = pHI;
    }

    public String getProductTradeName() {
        return productTradeName;
    }

    public void setProductTradeName(String productTradeName) {
        this.productTradeName = productTradeName;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public String getReasonForUse() {
        return reasonForUse;
    }

    public void setReasonForUse(String reasonForUse) {
        this.reasonForUse = reasonForUse;
    }

    public String getRegistrationNumber() {
        return registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    @Override
    public String toString() {
        return productTradeName;
    }


}
