package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FERTILIZER.
 */
public class Fertilizer {

    private Long fertilizerID;
    private String fertilizerType;
    private String mainNutrients;
    private String soilConditions;
    private Integer timeOfPlanting;
    private Integer topDressing;
    private Long cropID;

    public Fertilizer() {
    }

    public Fertilizer(Long fertilizerID) {
        this.fertilizerID = fertilizerID;
    }

    public Fertilizer(Long fertilizerID, String fertilizerType, String mainNutrients, String soilConditions, Integer timeOfPlanting, Integer topDressing, Long cropID) {
        this.fertilizerID = fertilizerID;
        this.fertilizerType = fertilizerType;
        this.mainNutrients = mainNutrients;
        this.soilConditions = soilConditions;
        this.timeOfPlanting = timeOfPlanting;
        this.topDressing = topDressing;
        this.cropID = cropID;
    }

    public Long getFertilizerID() {
        return fertilizerID;
    }

    public void setFertilizerID(Long fertilizerID) {
        this.fertilizerID = fertilizerID;
    }

    public String getFertilizerType() {
        return fertilizerType;
    }

    public void setFertilizerType(String fertilizerType) {
        this.fertilizerType = fertilizerType;
    }

    public String getMainNutrients() {
        return mainNutrients;
    }

    public void setMainNutrients(String mainNutrients) {
        this.mainNutrients = mainNutrients;
    }

    public String getSoilConditions() {
        return soilConditions;
    }

    public void setSoilConditions(String soilConditions) {
        this.soilConditions = soilConditions;
    }

    public Integer getTimeOfPlanting() {
        return timeOfPlanting;
    }

    public void setTimeOfPlanting(Integer timeOfPlanting) {
        this.timeOfPlanting = timeOfPlanting;
    }

    public Integer getTopDressing() {
        return topDressing;
    }

    public void setTopDressing(Integer topDressing) {
        this.topDressing = topDressing;
    }

    public Long getCropID() {
        return cropID;
    }

    public void setCropID(Long cropID) {
        this.cropID = cropID;
    }

}
