package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FIELD.
 */
public class Field {

    private Long fieldID;
    private String fieldName;
    private String location;
    private Long farmerID;

    public Field() {
    }

    public Field(Long fieldID) {
        this.fieldID = fieldID;
    }

    public Field(Long fieldID, String fieldName, String location, Long farmerID) {
        this.fieldID = fieldID;
        this.fieldName = fieldName;
        this.location = location;
        this.farmerID = farmerID;
    }

    public Long getFieldID() {
        return fieldID;
    }

    public void setFieldID(Long fieldID) {
        this.fieldID = fieldID;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Long getFarmerID() {
        return farmerID;
    }

    public void setFarmerID(Long farmerID) {
        this.farmerID = farmerID;
    }

    @Override
    public String toString() {
        return "Field{" +
                "fieldID=" + fieldID +
                ", fieldName='" + fieldName + '\'' +
                ", location='" + location + '\'' +
                ", farmerID=" + farmerID +
                '}';
    }
}
