package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FIELD.
 */
public class Field {

    private Long fieldID;
    private String fieldName;
    private String location;
    private Double area;
    private Long farmerID;

    public Field() {
    }

    public Field(Long fieldID) {
        this.fieldID = fieldID;
    }

    public Field(Long fieldID, String fieldName, String location, Double area, Long farmerID) {
        this.fieldID = fieldID;
        this.fieldName = fieldName;
        this.location = location;
        this.area = area;
        this.farmerID = farmerID;
    }

    public Long getFieldID() {
        return fieldID;
    }

    public void setFieldID(Long fieldID) {
        this.fieldID = fieldID;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Double getArea() {
        return area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public Long getFarmerID() {
        return farmerID;
    }

    public void setFarmerID(Long farmerID) {
        this.farmerID = farmerID;
    }

}
