package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLANTING_ACTIVITY.
 */
public class PlantingActivity {

    private Long plantingActivityID;
    private Integer activityType;
    private String input;
    private Double quantity;
    private String location;
    private String activityDate;
    private Long userID;
    private Long fieldID;

    public PlantingActivity() {
    }

    public PlantingActivity(Long plantingActivityID) {
        this.plantingActivityID = plantingActivityID;
    }

    public PlantingActivity(Long plantingActivityID, Integer activityType, String input, Double quantity, String location, String activityDate, Long userID, Long fieldID) {
        this.plantingActivityID = plantingActivityID;
        this.activityType = activityType;
        this.input = input;
        this.quantity = quantity;
        this.location = location;
        this.activityDate = activityDate;
        this.userID = userID;
        this.fieldID = fieldID;
    }

    public Long getPlantingActivityID() {
        return plantingActivityID;
    }

    public void setPlantingActivityID(Long plantingActivityID) {
        this.plantingActivityID = plantingActivityID;
    }

    public Integer getActivityType() {
        return activityType;
    }

    public void setActivityType(Integer activityType) {
        this.activityType = activityType;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getActivityDate() {
        return activityDate;
    }

    public void setActivityDate(String activityDate) {
        this.activityDate = activityDate;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public Long getFieldID() {
        return fieldID;
    }

    public void setFieldID(Long fieldID) {
        this.fieldID = fieldID;
    }

}
