package net.azurewebsites.farmtrace.datamodel.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SEED.
 */
public class Seed {

    private Long seedID;
    private Integer seedRate;
    private String seedVariety;
    private Integer transplantToHarvest;
    private Long cropID;

    public Seed() {
    }

    public Seed(Long seedID) {
        this.seedID = seedID;
    }

    public Seed(Long seedID, Integer seedRate, String seedVariety, Integer transplantToHarvest, Long cropID) {
        this.seedID = seedID;
        this.seedRate = seedRate;
        this.seedVariety = seedVariety;
        this.transplantToHarvest = transplantToHarvest;
        this.cropID = cropID;
    }

    public Long getSeedID() {
        return seedID;
    }

    public void setSeedID(Long seedID) {
        this.seedID = seedID;
    }

    public Integer getSeedRate() {
        return seedRate;
    }

    public void setSeedRate(Integer seedRate) {
        this.seedRate = seedRate;
    }

    public String getSeedVariety() {
        return seedVariety;
    }

    public void setSeedVariety(String seedVariety) {
        this.seedVariety = seedVariety;
    }

    public Integer getTransplantToHarvest() {
        return transplantToHarvest;
    }

    public void setTransplantToHarvest(Integer transplantToHarvest) {
        this.transplantToHarvest = transplantToHarvest;
    }

    public Long getCropID() {
        return cropID;
    }

    public void setCropID(Long cropID) {
        this.cropID = cropID;
    }

    @Override
    public String toString() {
        return seedVariety;
    }


}
